### ISSUE TITLE
I'm running on runpod but getting this error: ModuleNotFoundError: No module named 'tkinter'

### ISSUE THREAD

**Issue by poeticoncept** [Thund3rPat/kohya_ss-linux#20]
Getting this error when typing: python3 ./kohya_gui.py

ERROR: ModuleNotFoundError: No module named 'tkinter'

**Comment by moon47usaco** [comment]
Same... =\

```
(venv) root@88a8d94710cf:/workspace/kohya_ss-linux# python3 ./kohya_gui.py
Traceback (most recent call last):
  File "/workspace/kohya_ss-linux/./kohya_gui.py", line 4, in <module>
    from dreambooth_gui import dreambooth_tab
  File "/workspace/kohya_ss-linux/dreambooth_gui.py", line 13, in <module>
    from library.common_gui import (
  File "/workspace/kohya_ss-linux/library/common_gui.py", line 1, in <module>
    from tkinter import filedialog, Tk
ModuleNotFoundError: No module named 'tkinter'
```

**Comment by novitae** [comment]
Solved by doing:
- `source venv/bin/activate` *might be optional*
- `apt-get install python3.10-tk` *don't need to precise `.10` if you only have one version of python3*

**Comment by donlaiq** [comment]
I have a similar problem here, but in this case the message is 

`ModuleNotFoundError: No module named '_tkinter'`

with the underscore symbol.

**Comment by moon47usaco** [comment]
Try this tutorial from SECourses:
https://github.com/FurkanGozukara/Stable-Diffusion/blob/main/Tutorials/How-To-Install-Kohya-LoRA-Web-UI-On-RunPod.md
Working on runpod. Should be the same on any other Linux system

**Comment by donlaiq** [comment]
Thanks @moon47usaco, but it doesn't work for me.

**Comment by moon47usaco** [comment]
Did fastapi install without errors inside the venv?

**Comment by donlaiq** [comment]
@moon47usaco All the installation process runs flawlessly, except for this line

`apt-get install python3.10-tk`

I've even downgraded my version of Python from 3.11.x to 3.10.12 (and 3.10.7 before), but I can't find a way to install that package on Debian.

**Comment by moon47usaco** [comment]
Sorry can not help with Debian. I know nothing about it. Try the discord from the tutorial he is really helpful.

**Comment by donlaiq** [comment]
No worries, dude!
