### ISSUE TITLE
Error when training model 

### ISSUE THREAD

**Issue by zono50** [Thund3rPat/kohya_ss-linux#7]
Hey there, first wanted to say thank you for porting this over. I am trying to train a model currently, and am getting this error. 

Traceback (most recent call last):
  File "/home/zono50/kohya_ss-linux/train_network.py", line 548, in <module>
    train(args)
  File "/home/zono50/kohya_ss-linux/train_network.py", line 156, in train
    text_encoder, vae, unet, _ = train_util.load_target_model(args, weight_dtype)
  File "/home/zono50/kohya_ss-linux/library/train_util.py", line 1584, in load_target_model
    text_encoder, vae, unet = model_util.load_models_from_stable_diffusion_checkpoint(args.v2, args.pretrained_model_name_or_path)
  File "/home/zono50/kohya_ss-linux/library/model_util.py", line 880, in load_models_from_stable_diffusion_checkpoint
    info = unet.load_state_dict(converted_unet_checkpoint)
  File "/home/zono50/kohya_ss-linux/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1671, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for UNet2DConditionModel:
        size mismatch for conv_in.weight: copying a param with shape torch.Size([320, 9, 3, 3]) from checkpoint, the shape in current model is torch.Size([320, 4, 3, 3]).
Traceback (most recent call last):
  File "/home/zono50/kohya_ss-linux/venv/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/zono50/kohya_ss-linux/venv/lib/python3.9/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/home/zono50/kohya_ss-linux/venv/lib/python3.9/site-packages/accelerate/commands/launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "/home/zono50/kohya_ss-linux/venv/lib/python3.9/site-packages/accelerate/commands/launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/zono50/kohya_ss-linux/venv/bin/python3', 'train_network.py', '--enable_bucket', '--pretrained_model_name_or_path=/home/zono50/stable-diffusion-webui/models/Stable-diffusion/realisticVisionV13_v13-inpainting.ckpt', '--train_data_dir=/home/zono50/Lora_Training_Data/Test/image', '--resolution=512,512', '--output_dir=/home/zono50/Lora_Training_Data/Test/model', '--logging_dir=/home/zono50/Lora_Training_Data/Test/log', '--network_alpha=1', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=5e-5', '--unet_lr=0.0001', '--network_dim=8', '--output_name=Brando', '--lr_scheduler_num_cycles=1', '--learning_rate=0.0001', '--lr_scheduler=cosine', '--lr_warmup_steps=600', '--train_batch_size=1', '--max_train_steps=6000', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--seed=1234', '--cache_latents', '--bucket_reso_steps=64', '--xformers', '--use_8bit_adam', '--bucket_no_upscale']' returned non-zero exit status 1.

Seems no matter what settings I set to train Lora, I get this error, would love to know if there is a fix for this.

**Comment by Thund3rPat** [comment]
Hi, I can see that you are using the inpainting version of Realistic Vision. Can you check if the “normal” Version works?
